NGROK:
  TOKEN: YOUR_NGROK_TOKEN 
OPEN_AI:
  API_KEY: YOUR_OPEN_AI_API_KEY
  MODEL: 'gpt-3.5-turbo'
  HYPER_TOP_P: 0.5
  HYPER_TEMPERATURE: 0.0
  OPENAI_API_ERROR_LOG: "OPENAPI_ERROR_MSG.log"

DATABASE:
  DB_PREFIX: ChatGee

SETTINGS:
  CALLBACK: False
  NO_FRIEND_USE_LIMIT: 7
  ADVERTISEMENT_FREQUENCY: 17
  RESPONSE_SAFE_TIME: 3.4
  SYSTEM_PROMPT: |
          - ChatGee act as an English translator, spelling corrector and improver.
          - ChatGee translate User's prompt into English.
          - ChatGee replace simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences.
          - ChatGee keep the meaning same, but make them more literary.
          - ChatGee only reply the correction, the improvements and nothing else, do not write explanations.
          - ChatGee doens't answer to User's prompt, but just translate the last User's prompt.
          - If User prompt in English, ChatGee now act as an Korean translator.
          - ChatGee doesnt write explanations, but reply only tranlsated texts.
          
CONTENTS:
  SUPPORT_LINK: https://qr.kakaopay.com/Ej87lce5z9c408045

  GREETINGS:
    TITLE: 만나서 반갑습니다! 🤗😍👋👋👋
    TEXTS: |
          카톡에서 ChatGPT로 번역 🥳🎉
          어느 언어든지 영어로 번역하고
          문장을 수정해 줍니다!
          영어를 넣으시면 한국어로
          번역해 줍니다!

  EXPLAIN:
    TEXTS: |
          어떤 언어든지 영어로 번역!
            ‣ 영어로 번역하고 문장을 수정
            
          영어를 입력하면 한국어로 번역!
            ‣ 한국어로 입력해 줍니다!
  
  ADVERTISEMENT:
    TEXTS: |
          만나서 반갑습니다!
          많은 관심과 사랑 부탁드립니다!
    LINK: mailto:talkchatgpt@email.com

SERVER:
  HOST_NAME: 0.0.0.0
  PORT_NUMBER: 6959
  DEBUG_FLASK: False

